name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy updated code to Azure VM & Deploy
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@135.235.154.146 "
            cd /home/azureuser/Random-Password-Generator &&
            git pull &&
            docker build -t my-react-app . &&
            docker stop react-container || true &&
            docker rm react-container || true &&
            docker run -d -p 3000:80 --name react-container my-react-app
          "

      - name: Collect metrics & generate graphs
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@135.235.154.146 '
            cd /home/azureuser/Random-Password-Generator &&
            chmod +x collect_metrics.sh &&
            ./collect_metrics.sh &&
            sudo apt-get update &&
            sudo apt-get install -y python3 python3-pip &&
            pip3 install matplotlib pandas &&
            python3 plot_metrics.py
          '

      - name: Download performance logs from VM
        run: |
          scp -o StrictHostKeyChecking=no azureuser@135.235.154.146:/home/azureuser/Random-Password-Generator/*.log .
          scp -o StrictHostKeyChecking=no azureuser@135.235.154.146:/home/azureuser/Random-Password-Generator/*.png .

      - name: Upload performance artifacts
        uses: actions/upload-artifact@v4
        with:
          name: performance-artifacts
          path: |
            *.log
            *.png
